apiVersion: v2
description: A Helm chart for civil-damages-camunda-bpmn-definition App
name: civil-damages-camunda-bpmn-definition
home: https://github.com/hmcts/civil-damages-camunda-bpmn-definition
version: 0.0.1
maintainers:
  - name: HMCTS Unspecified team

dependencies:
  - name: java
    version: 3.2.1
    repository: '@hmctspublic'
  - name: ccd
    version: 4.3.3
    repository: '@hmctspublic'
    tags:
      - unspec-ccd-stack
  - name: xui-webapp
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: xui-webapp.enabled
  - name: idam-pr
    version: ~2.2.3
    repository: '@hmctspublic'
    condition: idam-pr.enabled
  - name: postgresql
    version: 8.9.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: camunda-bpm
    version: 0.0.12
    repository: '@hmctspublic'
    condition: camunda-bpm.enabled
