tags:
  unspec-ccd-stack: true

postgresql:
  enabled: true
  image:
    registry: hmctspublic.azurecr.io
    repository: imported/postgres
    tag: '11.3'
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE cmc WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "user-profile" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "camunda" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  securityContext:
    runAsUser: 0
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  persistence:
    enabled: false

java:
  applicationPort: 4000
  image: 'hmctspublic.azurecr.io/civil-damages/service:latest'
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    unspec:
      resourceGroup: unspec
      secrets:
        - unspec-idam-client-secret
        - microservicekey-unspec-service
        - system-update-user-username
        - system-update-user-password
        - AppInsightsInstrumentationKey
        - docmosis-api-key
        - gov-notify-api-key
        - sendgrid-api-key
        - robotics-notification-sender
        - robotics-notification-recipient
        - launch-darkly-sdk-key
  environment:
    IDAM_CLIENT_ID: unspec-service
    IDAM_CLIENT_REDIRECT_URI: https://civil-damages-ccd-definition-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    MANAGE_CASE_UI_BASE_URL: https://manage-case.{{ .Values.global.environment }}.platform.hmcts.net
    SPRING_SECURITY_ENABLED: true
    CMC_DB_PORT: 5432
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/jwks
    AUTH_IDAM_CLIENT_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
    TESTING_SUPPORT_ENABLED: true
    FEES_API_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PAYMENTS_API_URL: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOCMOSIS_TORNADO_URL: https://docmosis-development.platform.hmcts.net
    DOCUMENT_MANAGEMENT_URL: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SPRING_CLOUD_BOOTSTRAP_ENABLED: true
    RD_PROFESSIONAL_API_URL: http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    LAUNCH_DARKLY_ENV: ${SERVICE_FQDN}
    CORE_CASE_DATA_API_URL: http://${SERVICE_NAME}-ccd-data-store-api
    CMC_DB_HOST: ${SERVICE_NAME}-postgresql
    CMC_DB_CONNECTION_OPTIONS: '?sslmode=allow'
    CMC_DB_USERNAME: hmcts
    CMC_DB_PASSWORD: hmcts
    REFERENCE_DATABASE_MIGRATION: true
    FEIGN_CLIENT_CONFIG_REMOTERUNTIMESERVICE_URL: http://camunda-${SERVICE_FQDN}/engine-rest/
    FEIGN_CLIENT_CONFIG_REMOTEEXTERNALTASKSERVICE_URL: http://camunda-${SERVICE_FQDN}/engine-rest/
    FEIGN_CLIENT_CONFIG_REMOTEREPOSITORYSERVICE_URL: http://camunda-${SERVICE_FQDN}/engine-rest/

idam-pr:
  releaseNameOverride: ${SERVICE_NAME}-xui-idam-pr
  enabled: true
  redirect_uris:
    XUI:
      - https://xui-${SERVICE_FQDN}/oauth2/callback

xui-webapp:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-xui-webapp
    image: hmctspublic.azurecr.io/xui/webapp:latest
    ingressHost: xui-${SERVICE_FQDN}
    environment:
      HEALTH_CCD_COMPONENT_API: http://gateway-${SERVICE_FQDN}/health
      HEALTH_CCD_DATA_API: http://${SERVICE_NAME}-ccd-data-store-api/health
      HEALTH_TERMS_AND_CONDITIONS_API: http://xui-terms-and-conditions-${SERVICE_FQDN}.service.core-compute-preview.internal/health
      SERVICES_CCD_COMPONENT_API: http://gateway-${SERVICE_FQDN}
      SERVICES_CCD_DATA_STORE_API: http://${SERVICE_NAME}-ccd-data-store-api
      SERVICES_TERMS_AND_CONDITIONS: http://xui-terms-and-conditions-${SERVICE_FQDN}.service.core-compute-preview.internal
      JURISDICTIONS: CIVIL
      LAUNCH_DARKLY_CLIENT_ID: ~

ccd:
  ccd:
    adminWeb:
      enabled: false
    apiGatewayWeb:
      enabled: true
    definitionImporter:
      enabled: false
    managementWeb:
      enabled: true
    s2s:
      enabled: false
    postgresql:
      enabled: false

  global:
    ccdApiGatewayIngress: gateway-${SERVICE_FQDN}
    ccdCaseManagementWebIngress: case-management-web-${SERVICE_FQDN}
    ccdDataStoreUrl: http://${SERVICE_NAME}-ccd-data-store-api
    ccdDefinitionStoreUrl: http://${SERVICE_NAME}-ccd-definition-store
    ccdUserProfileUrl: http://${SERVICE_NAME}-ccd-user-profile-api
    dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
    idamApiUrl: https://idam-api.aat.platform.hmcts.net
    idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
    s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal

  ccd-api-gateway-web:
    nodejs:
      imagePullPolicy: Always
      environment:
        ADDRESS_LOOKUP_TOKEN: ${ADDRESS_LOOKUP_TOKEN}
        IDAM_SERVICE_KEY: ${CCD_API_GATEWAY_S2S_SECRET}
        IDAM_OAUTH2_CLIENT_SECRET: ${CCD_API_GATEWAY_IDAM_CLIENT_SECRET}
        PROXY_DOCUMENT_MANAGEMENT: http://dm-store-aat.service.core-compute-aat.internal
      ingressHost: gateway-${SERVICE_FQDN}
      ingressIP: ${INGRESS_IP}
      keyVaults: []
  ccd-data-store-api:
    java:
      imagePullPolicy: Always
      environment:
        DATA_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DATA_STORE_IDAM_KEY: ${CCD_DATA_STORE_S2S_SECRET}
        DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_ps,bulk_scan_orchestrator,ccpay_bubble,ctsc_work_allocation,em_ccd_orchestrator,xui_webapp,unspec_service
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
        CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: unspec_service
      keyVaults: []
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}
  ccd-definition-store-api:
    java:
      imagePullPolicy: Always
      environment:
        DEFINITION_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DEFINITION_STORE_IDAM_KEY: ${CCD_DEFINITION_STORE_S2S_SECRET}
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
      keyVaults: []
      ingressHost: ccd-definition-store-${SERVICE_FQDN}
  ccd-user-profile-api:
    java:
      imagePullPolicy: Always
      enviroment:
        USER_PROFILE_DB_HOST: ${SERVICE_NAME}-postgresql
      keyVaults: []
      ingressHost: ccd-user-profile-api-${SERVICE_FQDN}

  postgresql:
    persistence:
      enabled: false

camunda-bpm:
  enabled: true
  java:
    disableKeyVaults: true
    releaseNameOverride: ${SERVICE_NAME}-camunda
    ingressHost: camunda-${SERVICE_FQDN}
    environment:
      CAMUNDA_API_AUTH_ENABLED: false
      CAMUNDA_DB_HOST: ${SERVICE_NAME}-postgresql
      CAMUNDA_DB_NAME: camunda
      CAMUNDA_DB_USER_NAME: hmcts
      CAMUNDA_DB_PASSWORD: hmcts
      CAMUNDA_BPM_DATABASE_SCHEMA_UPDATE: true
      S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      CAMUNDA_DB_CONN_OPTIONS: ""
